# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sveYq8Yd3exRtAUPE5YmYumwBH8p9UqX
"""

import torch
import torch.nn as nn

model  = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)

X = torch.tensor([[0.,0.], [0.,1.], [1., 0.],[1.,1.]])
y = torch.tensor([[0.], [1.], [1.], [0.]])
